creation of python environment :
- python -m venv nk
- .\nk\Scripts\activate
- default environment name is venv but you can custom 
- now select kernel >> python environment >> creted env
- install ipkernel package

Question :  
1. uv log
2. array vs list 
3. flatten() vs ravel()

In [ ]:
! pippip install numpy
import numpy as np

In [3]:
## converts list --> array
lst = [1,2,3,4]
print("my list : ",lst)
print("Type of my list : ",type(lst))
arr = np.array(lst)
print("my array : ",arr)
print("Type of my array : ",type(arr))


my list :  [1, 2, 3, 4]
Type of my list :  <class 'list'>
my array :  [1 2 3 4]
Type of my array :  <class 'numpy.ndarray'>


In [6]:
## list using range function
lst = list(range(8)) # define a range and then typecast it to list
# range() used to get element between specific range
print(lst,type(lst))
arr = np.array(lst)
print(arr,type(arr))


[0, 1, 2, 3, 4, 5, 6, 7] <class 'list'>
[0 1 2 3 4 5 6 7] <class 'numpy.ndarray'>


In [ ]:
arr = np.arange(2,22) ## array using range function 
print(arr,type(arr))


[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] <class 'numpy.ndarray'>


In [ ]:
arr = np.zeros(10) ## array of 0 and 10 is no of elements 
print(arr)
# 2-D np.zeros((rows,columns))
arr1 = np.zeros((5,10)) ## 5 is number of rows and 10 is number of columns
print(arr1)
print(arr1)

print(type(arr[1])) ## type of element is float that's why is goves output as 0.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.float64'>


In [ ]:
arr = np.ones(10) ## array of 1
print(arr)
# 2-D
arr1 = np.ones((5,10)) ## 5 is number of rows and 10 is number of columns
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
arr2 = np.linspace(1,10,5) ## 1 to 10 is a range and total elements is 5
print(arr2)

[ 1.    3.25  5.5   7.75 10.  ]


converts 1-D array to 2-D array using reshape()

In [ ]:
arr = np.arange(0,30)
print(arr)
# 1-D to 2-D reshape is used to change the dimensions of the arrayd
arr = arr.reshape(5,6) ## 5 is rows and 6 is columns
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [ ]:
# random : return random numbers within defined range
# random.randint() : random numbers are of integer type
arr = np.random.randint(1,5,10) ## range = 1 to 5 and 10 is total elements
arr

array([2, 4, 3, 2, 4, 4, 2, 4, 1, 1], dtype=int32)

In [ ]:
arr = np.random.randint(1,5,(2,5)) ## range = 1 to 5 and 2 is row and 5 is column and 2*5=10 are elements
arr

array([[4, 4, 1, 1, 3],
       [1, 3, 4, 3, 1]], dtype=int32)

In [ ]:
# random.random() :  random numbers are of float type
# - default range is 0.0 to 1.0
arr = np.random.random(10) ## 1-D
arr

array([0.46645268, 0.13621314, 0.65716522, 0.9182823 , 0.04056444,
       0.33238865, 0.99768069, 0.07697794, 0.74643673, 0.93454447])

In [ ]:
arr = np.random.random((3,5)) ## 2-D 
arr

array([[0.56911502, 0.10928863, 0.09881727, 0.0804297 , 0.52870804],
       [0.98823008, 0.53413213, 0.98671127, 0.94051369, 0.65706702],
       [0.03270231, 0.52811202, 0.01774126, 0.93994142, 0.93518631]])

Array Attribute


In [26]:
arr = np.arange(15)


In [28]:
arr = arr.reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
print("shape : ",arr.shape)
print("data type : ",arr.dtype)
print("size : ",arr.size)
print("dimensions : ",arr.ndim)

shape :  (3, 5)
data type :  int64
size :  15
dimensions :  2


In [35]:
print("indexing :  ",arr[1][3])
print("indexing :  ",arr[-1][-1])

print("indexing :  ",arr[2,4])
arr[-1][-1]=100
arr

indexing :   8
indexing :   14
indexing :   14


array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13, 100]])

In [ ]:
# array slicing:


In [67]:
arr = arr.T # t -> transpose : rows --> columns and columns --> rows
print(arr)

[[ 0  5 10 15 20 25 30 35 40 45 50 55]
 [ 1  6 11 16 21 26 31 36 41 46 51 56]
 [ 2  7 12 17 22 27 32 37 42 47 52 57]
 [ 3  8 13 18 23 28 33 38 43 48 53 58]
 [ 4  9 14 19 24 29 34 39 44 49 54 59]]


In [ ]:
## 2-D to 1-D
arr = arr.flatten()
print(arr)
print(arr.ndim)

[  0   5  10   1   6  11   2   7  12   3   8  13   4   9 100]
1


In [ ]:
arr1 = np.arange(60).reshape(12,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr1.ravel() # multiple dimension to 1-D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

3-D Array

In [ ]:
arr3 = np.arange(225).reshape(5,15,3) ## (tables,rows,columns) 
  ## 5 -> tables , 15 -> rows , 3 -> columns
arr3

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [42]:
print("shape : ",arr3.shape)
print("data type : ",arr3.dtype)
print("size : ",arr3.size)
print("dimensions : ",arr3.ndim)

shape :  (5, 15, 3)
data type :  int64
size :  225
dimensions :  3


indexing and slicing in 3-D

In [43]:
print(arr3[0])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]]


In [44]:
print(arr3[0][0])

[0 1 2]


In [55]:
## first element of each row of each table
print(arr3[0:5,0:15,0])

[[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42]
 [ 45  48  51  54  57  60  63  66  69  72  75  78  81  84  87]
 [ 90  93  96  99 102 105 108 111 114 117 120 123 126 129 132]
 [135 138 141 144 147 150 153 156 159 162 165 168 171 174 177]
 [180 183 186 189 192 195 198 201 204 207 210 213 216 219 222]]


In [ ]:
## first element of each table
print(arr3[0:4,0,0])
print(arr3[0:4][0][0]) # doesn't work properly why ?

[  0  45  90 135]
[0 1 2]


array operations

In [69]:

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [71]:
print(arr + 2 )
print(arr*2)
print(arr1/arr2)
print(arr1*arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1**2)
print(arr1**3)

[ 3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12 14 16 18 20]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  1   4   9  16  25  36  49  64  81 100]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[   1    8   27   64  125  216  343  512  729 1000]


In [73]:
print(arr.sort())

None
